# Generated by Django 5.2 on 2025-04-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingUser',
        ),
    ]
