# Generated by Django 5.2 on 2025-04-17 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_artwork'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artish',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='artish',
            name='portfolio_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artish',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='artish/profile/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in inches', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/cover/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='medium',
            field=models.CharField(blank=True, choices=[('oil', 'Oil'), ('acrylic', 'Acrylic'), ('watercolor', 'Watercolor'), ('digital', 'Digital'), ('ink', 'Ink'), ('mixed', 'Mixed Media')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='artwork',
            name='style',
            field=models.CharField(blank=True, choices=[('abstract', 'Abstract'), ('realism', 'Realism'), ('surrealism', 'Surrealism'), ('modern', 'Modern'), ('traditional', 'Traditional'), ('pop', 'Pop Art')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in inches', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='year_created',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/images/'),
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artworks/gallery/')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.artwork')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
