# Generated by Django 5.2 on 2025-04-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_artish_updated_at_artish_portfolio_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artish',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
